-- Telehealth MVP Database Schema for Supabase
-- version 1.0

-- This schema is designed to work with Supabase's built-in auth system.
-- It assumes that the `auth.users` table exists and contains user authentication info.

-- 1. PROFILES
-- Stores public user information, linked one-to-one with `auth.users`.
CREATE TABLE public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('patient', 'doctor', 'admin')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);
COMMENT ON TABLE public.profiles IS 'Stores public user information, linked to auth.users.';

-- 2. DOCTOR_DETAILS
-- Stores information specific to users with the 'doctor' role.
CREATE TABLE public.doctor_details (
  user_id UUID PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
  specialization TEXT,
  license_number TEXT NOT NULL,
  years_of_experience INT NOT NULL,
  bio TEXT
);
COMMENT ON TABLE public.doctor_details IS 'Stores professional information for doctors.';

-- 3. AVAILABILITY_SLOTS
-- Stores time slots when doctors are available for consultations.
CREATE TABLE public.availability_slots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doctor_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  start_time TIMESTAMPTZ NOT NULL,
  end_time TIMESTAMPTZ NOT NULL,
  is_booked BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
COMMENT ON TABLE public.availability_slots IS 'Time slots when doctors are available.';

-- 4. APPOINTMENTS
-- Tracks booked consultations between patients and doctors.
CREATE TABLE public.appointments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  doctor_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  slot_id BIGINT REFERENCES public.availability_slots(id) ON DELETE SET NULL,
  consultation_type TEXT NOT NULL CHECK (consultation_type IN ('video', 'chat')),
  status TEXT NOT NULL CHECK (status IN ('requested', 'accepted', 'rejected', 'completed', 'cancelled')) DEFAULT 'requested',
  created_at TIMESTAMPTZ DEFAULT NOW()
);
COMMENT ON TABLE public.appointments IS 'Tracks consultation bookings.';

-- 5. PRESCRIPTIONS
-- Stores prescription details generated by a doctor for a patient.
CREATE TABLE public.prescriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  appointment_id BIGINT NOT NULL REFERENCES public.appointments(id) ON DELETE CASCADE,
  patient_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  doctor_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  pdf_url TEXT NOT NULL,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
COMMENT ON TABLE public.prescriptions IS 'Stores prescription details and a link to the PDF.';

-- 6. FAMILIES
-- Defines a family unit for the subscription plan.
CREATE TABLE public.families (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  family_name TEXT NOT NULL,
  subscription_status TEXT CHECK (subscription_status IN ('active', 'inactive', 'trial')) DEFAULT 'trial',
  created_at TIMESTAMPTZ DEFAULT NOW()
);
COMMENT ON TABLE public.families IS 'Defines a family unit for subscription plans.';

-- 7. FAMILY_MEMBERS
-- Links users (patients) to a family.
CREATE TABLE public.family_members (
  family_id BIGINT NOT NULL REFERENCES public.families(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  PRIMARY KEY (family_id, user_id)
);
COMMENT ON TABLE public.family_members IS 'Links users to a family.';

-- 8. CHAT_MESSAGES
-- Stores messages for chat consultations.
CREATE TABLE public.chat_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  appointment_id BIGINT NOT NULL REFERENCES public.appointments(id) ON DELETE CASCADE,
  sender_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
COMMENT ON TABLE public.chat_messages IS 'Stores messages for a chat consultation.';


--- ROW LEVEL SECURITY (RLS) POLICIES ---
-- RLS ensures that users can only access data they are supposed to.

-- PROFILES
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own profile." ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can create their own profile." ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update their own profile." ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- DOCTOR_DETAILS
ALTER TABLE public.doctor_details ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can view doctor details." ON public.doctor_details FOR SELECT USING (true);
CREATE POLICY "Doctors can create their own details." ON public.doctor_details FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Doctors can update their own details." ON public.doctor_details FOR UPDATE USING (auth.uid() = user_id);

-- APPOINTMENTS
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Patients and doctors can view their own appointments." ON public.appointments FOR SELECT USING (auth.uid() = patient_id OR auth.uid() = doctor_id);
CREATE POLICY "Patients can create appointments for themselves." ON public.appointments FOR INSERT WITH CHECK (auth.uid() = patient_id);
CREATE POLICY "Users can update their own appointments." ON public.appointments FOR UPDATE USING (auth.uid() = patient_id OR auth.uid() = doctor_id);

-- Add other RLS policies for prescriptions, chat, etc. as features are built.
-- For example, only doctors can create prescriptions, only participants can view chat messages.
ALTER TABLE public.prescriptions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Involved parties can view prescriptions." ON public.prescriptions FOR SELECT USING (auth.uid() = patient_id OR auth.uid() = doctor_id);
CREATE POLICY "Doctors can create prescriptions." ON public.prescriptions FOR INSERT WITH CHECK (
    auth.uid() = doctor_id AND
    (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'doctor'
);

ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Participants can view chat messages." ON public.chat_messages FOR SELECT USING (
    sender_id = auth.uid() OR
    auth.uid() IN (SELECT patient_id FROM public.appointments WHERE id = appointment_id) OR
    auth.uid() IN (SELECT doctor_id FROM public.appointments WHERE id = appointment_id)
);
CREATE POLICY "Participants can send chat messages." ON public.chat_messages FOR INSERT WITH CHECK (
    sender_id = auth.uid() AND
    (
        auth.uid() IN (SELECT patient_id FROM public.appointments WHERE id = appointment_id) OR
        auth.uid() IN (SELECT doctor_id FROM public.appointments WHERE id = appointment_id)
    )
);
